implemented controller, dto, mapper, new exception, getBookById method
DmytroV95/online-book-store pull request #2
Opened 2023-09-04 19:08 UTC by DmytroV95

2023-09-05 08:44 UTC, SaiyaJ1N commented
You have a great solution, let`s make it more better!

2023-09-05 08:48 UTC, SaiyaJ1N requested changes

2023-09-05 08:48 UTC, SaiyaJ1N commented on src/main/java/com/varukha/onlinebookstore/dto/CreateBookRequestDto.java
> +    private Long id;
Id field in CreateBookRequestDto should not be present

2023-09-05 08:48 UTC, SaiyaJ1N commented on src/main/java/com/varukha/onlinebookstore/service/impl/BookServiceImpl.java
> +        this.bookMapper = bookMapper;
We can use @RequiredArgsConstructor to automaticaly create and initialize all field

2023-09-05 19:27 UTC, SaiyaJ1N approved these changes
Great!

2023-09-06 14:15 UTC, vovasalyha approved these changes
GJ

2023-09-06 14:15 UTC, vovasalyha commented on src/main/java/com/varukha/onlinebookstore/repository/BookRepository.java
> +    Optional<Book> findBookById(Long id);
```suggestion
    Optional<Book> findById(Long id);
```

2023-09-06 18:36 UTC, merged