implemented pagination and sorting of output data, added swagger
DmytroV95/online-book-store pull request #5
Opened 2023-09-08 15:37 UTC by DmytroV95

2023-09-08 18:57 UTC, irynamekh approved these changes
Good job!

2023-09-11 14:32 UTC, vovasalyha requested changes
Solution of the task is good, but resolve merge conflicts (I suspect it's because of added validation starter which should be added in the previous task)

2023-09-12 07:02 UTC, nacenik approved these changes
LGTM! 👍

2023-09-12 07:02 UTC, nacenik commented on pom.xml
> +            <version>2.1.0</version>
i'd recommend you put this version inside properties

2023-09-12 20:21 UTC, merged